name: ambient-condition-sensor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ambient-condition-sensor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: compile
        run: |
          make -C ambient-condition-sensor/ compile
